// flow-typed signature: 0a2458ef1903ee548cc77d55f6eae730
// flow-typed version: <<STUB>>/commit-template_v^1.0.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'commit-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'commit-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'commit-template/lib/commit-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'commit-template/lib/commit-template.js' {
  declare module.exports: $Exports<'commit-template/lib/commit-template'>;
}
