// flow-typed signature: c057ef7e7c7d82d5becc476faeeedbe3
// flow-typed version: <<STUB>>/element-closest_v^3.0.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-closest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-closest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'element-closest/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'element-closest/browser.js' {
  declare module.exports: $Exports<'element-closest/browser'>;
}
declare module 'element-closest/index' {
  declare module.exports: $Exports<'element-closest'>;
}
declare module 'element-closest/index.js' {
  declare module.exports: $Exports<'element-closest'>;
}
