// flow-typed signature: 66f9a0281186f2a882619697d4bc4d2d
// flow-typed version: <<STUB>>/format-message_v^6.2.3/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'format-message'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'format-message' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'format-message/base-format-children' {
  declare module.exports: any;
}

declare module 'format-message/inferno' {
  declare module.exports: any;
}

declare module 'format-message/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'format-message/base-format-children.js' {
  declare module.exports: $Exports<'format-message/base-format-children'>;
}
declare module 'format-message/index' {
  declare module.exports: $Exports<'format-message'>;
}
declare module 'format-message/index.js' {
  declare module.exports: $Exports<'format-message'>;
}
declare module 'format-message/inferno.js' {
  declare module.exports: $Exports<'format-message/inferno'>;
}
declare module 'format-message/react.js' {
  declare module.exports: $Exports<'format-message/react'>;
}
