// flow-typed signature: 7c9089fa7071b1c28a1a897700f2f16a
// flow-typed version: <<STUB>>/is-color_v^1.0.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-color/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-color/index' {
  declare module.exports: $Exports<'is-color'>;
}
declare module 'is-color/index.js' {
  declare module.exports: $Exports<'is-color'>;
}
declare module 'is-color/test/index' {
  declare module.exports: $Exports<'is-color/test'>;
}
declare module 'is-color/test/index.js' {
  declare module.exports: $Exports<'is-color/test'>;
}
