// flow-typed signature: cbe3973aacbde900bc2adc68dc46189b
// flow-typed version: <<STUB>>/react-contenteditable_v^3.3.5/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-contenteditable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-contenteditable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-contenteditable/lib/react-contenteditable' {
  declare module.exports: any;
}

declare module 'react-contenteditable/lib/src/react-contenteditable' {
  declare module.exports: any;
}

declare module 'react-contenteditable/lib/tests/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-contenteditable/lib/react-contenteditable.js' {
  declare module.exports: $Exports<'react-contenteditable/lib/react-contenteditable'>;
}
declare module 'react-contenteditable/lib/src/react-contenteditable.js' {
  declare module.exports: $Exports<'react-contenteditable/lib/src/react-contenteditable'>;
}
declare module 'react-contenteditable/lib/tests/src/index' {
  declare module.exports: $Exports<'react-contenteditable/lib/tests/src'>;
}
declare module 'react-contenteditable/lib/tests/src/index.js' {
  declare module.exports: $Exports<'react-contenteditable/lib/tests/src'>;
}
