// flow-typed signature: 0e6dc6bfada25487d39424a4c98d5588
// flow-typed version: <<STUB>>/react-refresh-webpack-plugin_v^0.1.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-refresh-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-refresh-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-refresh-webpack-plugin/src/helpers/createRefreshTemplate' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/helpers' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/helpers/injectRefreshEntry' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/loader' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/CompileErrorTrace' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/PageHeader' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorFooter' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorHeader' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorStack' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/components/Spacer' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/containers/CompileErrorContainer' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/containers/RuntimeErrorContainer' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/theme' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/utils/formatFilename' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/overlay/utils/removeAllChildren' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/BabelDetectComponent' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/createSocket' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/errorEventHandlers' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/ErrorOverlayEntry' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/globals' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/RefreshModuleRuntime' {
  declare module.exports: any;
}

declare module 'react-refresh-webpack-plugin/src/runtime/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-refresh-webpack-plugin/src/helpers/createRefreshTemplate.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/helpers/createRefreshTemplate'>;
}
declare module 'react-refresh-webpack-plugin/src/helpers/index' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/helpers'>;
}
declare module 'react-refresh-webpack-plugin/src/helpers/index.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/helpers'>;
}
declare module 'react-refresh-webpack-plugin/src/helpers/injectRefreshEntry.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/helpers/injectRefreshEntry'>;
}
declare module 'react-refresh-webpack-plugin/src/index' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src'>;
}
declare module 'react-refresh-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src'>;
}
declare module 'react-refresh-webpack-plugin/src/loader.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/loader'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/CompileErrorTrace.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/CompileErrorTrace'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/PageHeader.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/PageHeader'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorFooter.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorFooter'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorHeader.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorHeader'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorStack.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/RuntimeErrorStack'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/components/Spacer.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/components/Spacer'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/containers/CompileErrorContainer.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/containers/CompileErrorContainer'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/containers/RuntimeErrorContainer.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/containers/RuntimeErrorContainer'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/index' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/index.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/theme.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/theme'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/utils/formatFilename.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/utils/formatFilename'>;
}
declare module 'react-refresh-webpack-plugin/src/overlay/utils/removeAllChildren.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/overlay/utils/removeAllChildren'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/BabelDetectComponent.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/BabelDetectComponent'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/createSocket.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/createSocket'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/errorEventHandlers.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/errorEventHandlers'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/ErrorOverlayEntry.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/ErrorOverlayEntry'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/globals.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/globals'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/RefreshModuleRuntime.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/RefreshModuleRuntime'>;
}
declare module 'react-refresh-webpack-plugin/src/runtime/utils.js' {
  declare module.exports: $Exports<'react-refresh-webpack-plugin/src/runtime/utils'>;
}
