// flow-typed signature: a45bc6bcf249a52e650d66e58f07a4be
// flow-typed version: <<STUB>>/stylelint-a11y_v^1.2.3/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-a11y/dist' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/content-property-no-static-value/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/content-property-no-static-value' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/font-size-is-readable/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/font-size-is-readable' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-display-none/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-display-none' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/obsoleteAttributes' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-element/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-element' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-obsolete-element/obsoleteElements' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-outline-none/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-outline-none' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-spread-text/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-spread-text' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-text-align-justify/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/no-text-align-justify' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/jest.config' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/jest.setup' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/recommended' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/content-property-no-static-value/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/content-property-no-static-value' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/font-size-is-readable/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/font-size-is-readable' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-display-none/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-display-none' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-attribute' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/obsoleteAttributes' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-element/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-element' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-obsolete-element/obsoleteElements' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-outline-none/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-outline-none' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-spread-text/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-spread-text' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-text-align-justify/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/no-text-align-justify' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus/__tests__' {
  declare module.exports: any;
}

declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-a11y/dist/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist'>;
}
declare module 'stylelint-a11y/dist/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist'>;
}
declare module 'stylelint-a11y/dist/rules/content-property-no-static-value/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/content-property-no-static-value/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/content-property-no-static-value/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/content-property-no-static-value/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/content-property-no-static-value/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/content-property-no-static-value'>;
}
declare module 'stylelint-a11y/dist/rules/content-property-no-static-value/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/content-property-no-static-value'>;
}
declare module 'stylelint-a11y/dist/rules/font-size-is-readable/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/font-size-is-readable/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/font-size-is-readable/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/font-size-is-readable/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/font-size-is-readable/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/font-size-is-readable'>;
}
declare module 'stylelint-a11y/dist/rules/font-size-is-readable/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/font-size-is-readable'>;
}
declare module 'stylelint-a11y/dist/rules/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules'>;
}
declare module 'stylelint-a11y/dist/rules/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules'>;
}
declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed'>;
}
declare module 'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/line-height-is-vertical-rhythmed'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-color-scheme/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-color-scheme/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-color-scheme'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-color-scheme/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-color-scheme'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-reduced-motion/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-reduced-motion/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-reduced-motion'>;
}
declare module 'stylelint-a11y/dist/rules/media-prefers-reduced-motion/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/media-prefers-reduced-motion'>;
}
declare module 'stylelint-a11y/dist/rules/no-display-none/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-display-none/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-display-none/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-display-none/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-display-none/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-display-none'>;
}
declare module 'stylelint-a11y/dist/rules/no-display-none/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-display-none'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-attribute/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-attribute/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-attribute'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-attribute'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-attribute/obsoleteAttributes.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-attribute/obsoleteAttributes'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-element/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-element/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-element/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-element/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-element/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-element'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-element/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-element'>;
}
declare module 'stylelint-a11y/dist/rules/no-obsolete-element/obsoleteElements.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-obsolete-element/obsoleteElements'>;
}
declare module 'stylelint-a11y/dist/rules/no-outline-none/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-outline-none/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-outline-none/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-outline-none/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-outline-none/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-outline-none'>;
}
declare module 'stylelint-a11y/dist/rules/no-outline-none/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-outline-none'>;
}
declare module 'stylelint-a11y/dist/rules/no-spread-text/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-spread-text/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-spread-text/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-spread-text/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-spread-text/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-spread-text'>;
}
declare module 'stylelint-a11y/dist/rules/no-spread-text/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-spread-text'>;
}
declare module 'stylelint-a11y/dist/rules/no-text-align-justify/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-text-align-justify/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-text-align-justify/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-text-align-justify/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/no-text-align-justify/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-text-align-justify'>;
}
declare module 'stylelint-a11y/dist/rules/no-text-align-justify/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/no-text-align-justify'>;
}
declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/selector-pseudo-class-focus/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/selector-pseudo-class-focus/__tests__'>;
}
declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus/index' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/selector-pseudo-class-focus'>;
}
declare module 'stylelint-a11y/dist/rules/selector-pseudo-class-focus/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/dist/rules/selector-pseudo-class-focus'>;
}
declare module 'stylelint-a11y/jest.config.js' {
  declare module.exports: $Exports<'stylelint-a11y/jest.config'>;
}
declare module 'stylelint-a11y/jest.setup.js' {
  declare module.exports: $Exports<'stylelint-a11y/jest.setup'>;
}
declare module 'stylelint-a11y/recommended.js' {
  declare module.exports: $Exports<'stylelint-a11y/recommended'>;
}
declare module 'stylelint-a11y/src/index' {
  declare module.exports: $Exports<'stylelint-a11y/src'>;
}
declare module 'stylelint-a11y/src/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src'>;
}
declare module 'stylelint-a11y/src/rules/content-property-no-static-value/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/content-property-no-static-value/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/content-property-no-static-value/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/content-property-no-static-value/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/content-property-no-static-value/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/content-property-no-static-value'>;
}
declare module 'stylelint-a11y/src/rules/content-property-no-static-value/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/content-property-no-static-value'>;
}
declare module 'stylelint-a11y/src/rules/font-size-is-readable/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/font-size-is-readable/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/font-size-is-readable/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/font-size-is-readable/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/font-size-is-readable/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/font-size-is-readable'>;
}
declare module 'stylelint-a11y/src/rules/font-size-is-readable/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/font-size-is-readable'>;
}
declare module 'stylelint-a11y/src/rules/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules'>;
}
declare module 'stylelint-a11y/src/rules/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules'>;
}
declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed'>;
}
declare module 'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/line-height-is-vertical-rhythmed'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-color-scheme/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-color-scheme/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-color-scheme'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-color-scheme/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-color-scheme'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-reduced-motion/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-reduced-motion/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-reduced-motion'>;
}
declare module 'stylelint-a11y/src/rules/media-prefers-reduced-motion/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/media-prefers-reduced-motion'>;
}
declare module 'stylelint-a11y/src/rules/no-display-none/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-display-none/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-display-none/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-display-none/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-display-none/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-display-none'>;
}
declare module 'stylelint-a11y/src/rules/no-display-none/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-display-none'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-attribute/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-attribute/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-attribute'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-attribute'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-attribute/obsoleteAttributes.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-attribute/obsoleteAttributes'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-element/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-element/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-element/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-element/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-element/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-element'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-element/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-element'>;
}
declare module 'stylelint-a11y/src/rules/no-obsolete-element/obsoleteElements.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-obsolete-element/obsoleteElements'>;
}
declare module 'stylelint-a11y/src/rules/no-outline-none/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-outline-none/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-outline-none/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-outline-none/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-outline-none/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-outline-none'>;
}
declare module 'stylelint-a11y/src/rules/no-outline-none/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-outline-none'>;
}
declare module 'stylelint-a11y/src/rules/no-spread-text/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-spread-text/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-spread-text/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-spread-text/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-spread-text/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-spread-text'>;
}
declare module 'stylelint-a11y/src/rules/no-spread-text/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-spread-text'>;
}
declare module 'stylelint-a11y/src/rules/no-text-align-justify/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-text-align-justify/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-text-align-justify/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-text-align-justify/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/no-text-align-justify/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-text-align-justify'>;
}
declare module 'stylelint-a11y/src/rules/no-text-align-justify/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/no-text-align-justify'>;
}
declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus/__tests__/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/selector-pseudo-class-focus/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus/__tests__/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/selector-pseudo-class-focus/__tests__'>;
}
declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus/index' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/selector-pseudo-class-focus'>;
}
declare module 'stylelint-a11y/src/rules/selector-pseudo-class-focus/index.js' {
  declare module.exports: $Exports<'stylelint-a11y/src/rules/selector-pseudo-class-focus'>;
}
