// flow-typed signature: 0590ac13d0f2fcede8f2ccdc4014ba25
// flow-typed version: <<STUB>>/textilejs_v^1.0.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'textilejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'textilejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'textilejs/lib/textile' {
  declare module.exports: any;
}

declare module 'textilejs/test/jquery' {
  declare module.exports: any;
}

declare module 'textilejs/test/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'textilejs/lib/textile.js' {
  declare module.exports: $Exports<'textilejs/lib/textile'>;
}
declare module 'textilejs/test/jquery.js' {
  declare module.exports: $Exports<'textilejs/test/jquery'>;
}
declare module 'textilejs/test/qunit.js' {
  declare module.exports: $Exports<'textilejs/test/qunit'>;
}
