// flow-typed signature: 37795034f6038cca218a21b62601280a
// flow-typed version: <<STUB>>/webpack-plugin-serve_v^1.1.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-plugin-serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-plugin-serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-plugin-serve/client' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/client' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/ClientSocket' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/hmr' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/log' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/overlays/progress-minimal' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/overlays/progress' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/overlays/status' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/client/overlays/util' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/errors' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/log' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/middleware' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/plugins/hmr' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/plugins/ramdisk' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/routes' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/server' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/validate' {
  declare module.exports: any;
}

declare module 'webpack-plugin-serve/lib/ws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-plugin-serve/client.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/client'>;
}
declare module 'webpack-plugin-serve/lib/client/client.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/client'>;
}
declare module 'webpack-plugin-serve/lib/client/ClientSocket.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/ClientSocket'>;
}
declare module 'webpack-plugin-serve/lib/client/hmr.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/hmr'>;
}
declare module 'webpack-plugin-serve/lib/client/log.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/log'>;
}
declare module 'webpack-plugin-serve/lib/client/overlays/progress-minimal.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/overlays/progress-minimal'>;
}
declare module 'webpack-plugin-serve/lib/client/overlays/progress.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/overlays/progress'>;
}
declare module 'webpack-plugin-serve/lib/client/overlays/status.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/overlays/status'>;
}
declare module 'webpack-plugin-serve/lib/client/overlays/util.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/client/overlays/util'>;
}
declare module 'webpack-plugin-serve/lib/errors.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/errors'>;
}
declare module 'webpack-plugin-serve/lib/index' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib'>;
}
declare module 'webpack-plugin-serve/lib/index.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib'>;
}
declare module 'webpack-plugin-serve/lib/log.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/log'>;
}
declare module 'webpack-plugin-serve/lib/middleware.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/middleware'>;
}
declare module 'webpack-plugin-serve/lib/plugins/hmr.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/plugins/hmr'>;
}
declare module 'webpack-plugin-serve/lib/plugins/ramdisk.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/plugins/ramdisk'>;
}
declare module 'webpack-plugin-serve/lib/routes.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/routes'>;
}
declare module 'webpack-plugin-serve/lib/server.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/server'>;
}
declare module 'webpack-plugin-serve/lib/validate.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/validate'>;
}
declare module 'webpack-plugin-serve/lib/ws.js' {
  declare module.exports: $Exports<'webpack-plugin-serve/lib/ws'>;
}
