// flow-typed signature: 7b1bf1463a73b381826133b79804fc75
// flow-typed version: <<STUB>>/xhr-mock_v^2.5.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xhr-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xhr-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xhr-mock/dist/xhr-mock' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/createMockFunction' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/createResponseFromObject' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/formatError' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/handle' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/index.umd' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/isPromiseLike' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockError' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockEvent' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockEventTarget' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockHeaders' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockProgressEvent' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockRequest' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockResponse' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockURL' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockXMLHttpRequest' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockXMLHttpRequestEventTarget' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/MockXMLHttpRequestUpload' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/proxy.browser' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/proxy' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/types' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/utils/delay' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/utils/once' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/utils/sequence' {
  declare module.exports: any;
}

declare module 'xhr-mock/lib/XHRMock' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xhr-mock/dist/xhr-mock.js' {
  declare module.exports: $Exports<'xhr-mock/dist/xhr-mock'>;
}
declare module 'xhr-mock/lib/createMockFunction.js' {
  declare module.exports: $Exports<'xhr-mock/lib/createMockFunction'>;
}
declare module 'xhr-mock/lib/createResponseFromObject.js' {
  declare module.exports: $Exports<'xhr-mock/lib/createResponseFromObject'>;
}
declare module 'xhr-mock/lib/formatError.js' {
  declare module.exports: $Exports<'xhr-mock/lib/formatError'>;
}
declare module 'xhr-mock/lib/handle.js' {
  declare module.exports: $Exports<'xhr-mock/lib/handle'>;
}
declare module 'xhr-mock/lib/index' {
  declare module.exports: $Exports<'xhr-mock/lib'>;
}
declare module 'xhr-mock/lib/index.js' {
  declare module.exports: $Exports<'xhr-mock/lib'>;
}
declare module 'xhr-mock/lib/index.umd.js' {
  declare module.exports: $Exports<'xhr-mock/lib/index.umd'>;
}
declare module 'xhr-mock/lib/isPromiseLike.js' {
  declare module.exports: $Exports<'xhr-mock/lib/isPromiseLike'>;
}
declare module 'xhr-mock/lib/MockError.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockError'>;
}
declare module 'xhr-mock/lib/MockEvent.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockEvent'>;
}
declare module 'xhr-mock/lib/MockEventTarget.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockEventTarget'>;
}
declare module 'xhr-mock/lib/MockHeaders.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockHeaders'>;
}
declare module 'xhr-mock/lib/MockProgressEvent.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockProgressEvent'>;
}
declare module 'xhr-mock/lib/MockRequest.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockRequest'>;
}
declare module 'xhr-mock/lib/MockResponse.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockResponse'>;
}
declare module 'xhr-mock/lib/MockURL.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockURL'>;
}
declare module 'xhr-mock/lib/MockXMLHttpRequest.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockXMLHttpRequest'>;
}
declare module 'xhr-mock/lib/MockXMLHttpRequestEventTarget.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockXMLHttpRequestEventTarget'>;
}
declare module 'xhr-mock/lib/MockXMLHttpRequestUpload.js' {
  declare module.exports: $Exports<'xhr-mock/lib/MockXMLHttpRequestUpload'>;
}
declare module 'xhr-mock/lib/proxy.browser.js' {
  declare module.exports: $Exports<'xhr-mock/lib/proxy.browser'>;
}
declare module 'xhr-mock/lib/proxy.js' {
  declare module.exports: $Exports<'xhr-mock/lib/proxy'>;
}
declare module 'xhr-mock/lib/types.js' {
  declare module.exports: $Exports<'xhr-mock/lib/types'>;
}
declare module 'xhr-mock/lib/utils/delay.js' {
  declare module.exports: $Exports<'xhr-mock/lib/utils/delay'>;
}
declare module 'xhr-mock/lib/utils/once.js' {
  declare module.exports: $Exports<'xhr-mock/lib/utils/once'>;
}
declare module 'xhr-mock/lib/utils/sequence.js' {
  declare module.exports: $Exports<'xhr-mock/lib/utils/sequence'>;
}
declare module 'xhr-mock/lib/XHRMock.js' {
  declare module.exports: $Exports<'xhr-mock/lib/XHRMock'>;
}
