// flow-typed signature: cf23b257f6a9ddaf302db423697ff0f7
// flow-typed version: <<STUB>>/yarpm_v^0.2.1/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarpm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarpm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yarpm/bin/bin-executor' {
  declare module.exports: any;
}

declare module 'yarpm/bin/yarpm-yarn' {
  declare module.exports: any;
}

declare module 'yarpm/bin/yarpm' {
  declare module.exports: any;
}

declare module 'yarpm/lib/detect-stream-kind' {
  declare module.exports: any;
}

declare module 'yarpm/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yarpm/bin/bin-executor.js' {
  declare module.exports: $Exports<'yarpm/bin/bin-executor'>;
}
declare module 'yarpm/bin/yarpm-yarn.js' {
  declare module.exports: $Exports<'yarpm/bin/yarpm-yarn'>;
}
declare module 'yarpm/bin/yarpm.js' {
  declare module.exports: $Exports<'yarpm/bin/yarpm'>;
}
declare module 'yarpm/lib/detect-stream-kind.js' {
  declare module.exports: $Exports<'yarpm/lib/detect-stream-kind'>;
}
declare module 'yarpm/lib/index' {
  declare module.exports: $Exports<'yarpm/lib'>;
}
declare module 'yarpm/lib/index.js' {
  declare module.exports: $Exports<'yarpm/lib'>;
}
