// flow-typed signature: a9a887c5a5713a2225561a8c380212e4
// flow-typed version: <<STUB>>/@babel/plugin-transform-named-capturing-groups-regex_v^7.10.4/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-named-capturing-groups-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-named-capturing-groups-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-named-capturing-groups-regex/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-named-capturing-groups-regex/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-named-capturing-groups-regex/lib'>;
}
declare module '@babel/plugin-transform-named-capturing-groups-regex/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-named-capturing-groups-regex/lib'>;
}
