// flow-typed signature: 6aab80c90580acbffc88a8e861e81715
// flow-typed version: <<STUB>>/@pmmmwh/react-refresh-webpack-plugin_v^0.4.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@pmmmwh/react-refresh-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@pmmmwh/react-refresh-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/client/LegacyWDSSocketEntry' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/errorEventHandlers' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/formatWebpackErrors' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/safeThis' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/globals' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshRuntimeModule' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/types' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/createError' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getParserHelpers' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getRefreshGlobal' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getSocketIntegration' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshEntry' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshLoader' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/normalizeOptions' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/loader' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/loader/RefreshModule.runtime' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/loader/RefreshSetup.runtime' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/CompileErrorTrace' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/PageHeader' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorHeader' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorStack' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/Spacer' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/containers/CompileErrorContainer' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/containers/RuntimeErrorContainer' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/theme' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/debounce' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/formatFilename' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/removeAllChildren' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getCurrentScriptSource' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getSocketUrlParts' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/parseQuery' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WDSSocket' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WHMEventSource' {
  declare module.exports: any;
}

declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WPSSocket' {
  declare module.exports: any;
}

// Filename aliases
declare module '@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/client/LegacyWDSSocketEntry.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/LegacyWDSSocketEntry'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/errorEventHandlers.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/utils/errorEventHandlers'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/formatWebpackErrors.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/utils/formatWebpackErrors'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/client/utils/safeThis.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/client/utils/safeThis'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/globals.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/globals'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/index' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshRuntimeModule.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshRuntimeModule'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/types.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/types'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/createError.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/createError'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getParserHelpers.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/getParserHelpers'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getRefreshGlobal.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/getRefreshGlobal'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/getSocketIntegration.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/getSocketIntegration'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/index' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/index.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshEntry.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshEntry'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshLoader.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/injectRefreshLoader'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/lib/utils/normalizeOptions.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/lib/utils/normalizeOptions'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/loader/index' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/loader'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/loader/index.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/loader'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/loader/RefreshModule.runtime.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/loader/RefreshModule.runtime'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/loader/RefreshSetup.runtime.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/loader/RefreshSetup.runtime'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/CompileErrorTrace.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/CompileErrorTrace'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/PageHeader.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/PageHeader'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorHeader.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorHeader'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorStack.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorStack'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/components/Spacer.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/components/Spacer'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/containers/CompileErrorContainer.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/containers/CompileErrorContainer'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/containers/RuntimeErrorContainer.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/containers/RuntimeErrorContainer'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/index' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/index.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/theme.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/theme'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/debounce.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/utils/debounce'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/formatFilename.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/utils/formatFilename'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/overlay/utils/removeAllChildren.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/overlay/utils/removeAllChildren'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getCurrentScriptSource.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getCurrentScriptSource'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getSocketUrlParts.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/utils/getSocketUrlParts'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/utils/parseQuery.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/utils/parseQuery'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WDSSocket.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/WDSSocket'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WHMEventSource.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/WHMEventSource'>;
}
declare module '@pmmmwh/react-refresh-webpack-plugin/sockets/WPSSocket.js' {
  declare module.exports: $Exports<'@pmmmwh/react-refresh-webpack-plugin/sockets/WPSSocket'>;
}
