// flow-typed signature: fcb63032887c75fe2bc01ad3a504fec3
// flow-typed version: <<STUB>>/@mdi/font_v^5.6.55/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/font'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/font' {
  declare module.exports: any;
}
