// flow-typed signature: 25bff095f78b91249dc990194021ed6e
// flow-typed version: <<STUB>>/@mdi/react_v^1.4.0/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdi/react/Icon' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdi/react/Icon.js' {
  declare module.exports: $Exports<'@mdi/react/Icon'>;
}
