// flow-typed signature: 3640edae6b71a8660dabb482b4f5d6ef
// flow-typed version: <<STUB>>/@storybook/addon-console_v^1.2.2/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-console/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-console/dist/react-decorator' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-console/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-console/dist'>;
}
declare module '@storybook/addon-console/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-console/dist'>;
}
declare module '@storybook/addon-console/dist/react-decorator.js' {
  declare module.exports: $Exports<'@storybook/addon-console/dist/react-decorator'>;
}
