// flow-typed signature: 1e00a4ea4cb78fc07f640e9a50db2c19
// flow-typed version: <<STUB>>/@storybook/source-loader_v^5.3.19/flow_v0.135.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/source-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/source-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/source-loader/dist/client/events' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/default-options' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/generate-helpers' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/inject-decorator' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parse-helpers' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-flow' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-js' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-ts' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/traverse-helpers' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/build' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/dependencies-lookup/getRidOfUselessFilePrefixes' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server/dependencies-lookup/readAsObject' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/dist/server' {
  declare module.exports: any;
}

declare module '@storybook/source-loader/preview' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/source-loader/dist/client/events.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/client/events'>;
}
declare module '@storybook/source-loader/dist/client/preview.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/client/preview'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/default-options.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/default-options'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/generate-helpers.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/generate-helpers'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/inject-decorator.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/inject-decorator'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parse-helpers.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parse-helpers'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/index' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parsers'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/index.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parsers'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-flow.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-flow'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-js.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-js'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-ts.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/parsers/parser-ts'>;
}
declare module '@storybook/source-loader/dist/server/abstract-syntax-tree/traverse-helpers.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/abstract-syntax-tree/traverse-helpers'>;
}
declare module '@storybook/source-loader/dist/server/build.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/build'>;
}
declare module '@storybook/source-loader/dist/server/dependencies-lookup/getRidOfUselessFilePrefixes.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/dependencies-lookup/getRidOfUselessFilePrefixes'>;
}
declare module '@storybook/source-loader/dist/server/dependencies-lookup/readAsObject.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server/dependencies-lookup/readAsObject'>;
}
declare module '@storybook/source-loader/dist/server/index' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server'>;
}
declare module '@storybook/source-loader/dist/server/index.js' {
  declare module.exports: $Exports<'@storybook/source-loader/dist/server'>;
}
declare module '@storybook/source-loader/preview.js' {
  declare module.exports: $Exports<'@storybook/source-loader/preview'>;
}
